INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '효과적인 의사 전달 및 설득력 있는 커뮤니케이션 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '명확하고 간결한 문서 작성 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '팀원들과의 원활한 대화 및 협업 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '문제를 해결하고 새로운 방법을 찾는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '논리적이고 체계적인 접근 방식');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '복잡한 문제를 해결하기 위한 창의성과 융통성');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '빠르게 변화하는 환경에서의 적응력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '새로운 기술과 도구에 대한 학습 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '유연성과 변화에 대한 긍정적인 태도');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '팀을 이끄는 능력과 리더십');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '다른 팀원들을 동기부여하고 지원하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '의사 결정 능력과 책임감');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '팀원들과의 협력과 상호 작용 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '효과적인 팀 구성원으로서의 역할 수행');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '타인의 의견을 존중하고 수용하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '일정을 관리하고 우선 순위를 정하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '프로젝트의 일정을 지키고 업무를 효율적으로 수행하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '일과 개인 생활의 균형 유지');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '새로운 아이디어를 발굴하고 구현하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '문제에 대한 다양한 접근 방식과 해결책 제시');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '혁신적인 제품이나 서비스를 위한 아이디어 발전');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '다른 사람과의 관계 구축과 유지 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '이해심과 공감능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '갈등 관리 및 해결 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '문제를 스스로 파악하고 해결하기 위한 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '적극적으로 일을 추진하고 주도하는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '자신의 업무와 조직의 목표에 대한 책임감');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '정보를 수집하고 분석하여 결정을 내리는 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '복잡한 상황에서의 의사 결정 능력');
INSERT INTO soft_skill (ss_code, ss_name) VALUES (soft_skill_seq.nextval, '리스크를 고려하고 책임 있는 결정을 내리는 능력');